name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          token: ${{ secrets.pat }}