name: Automatic Approve
on: pull_request_target

jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        environment:
          name: test
        with:
          token: ${{ secrets.PAT || || github.token}}
          workflows: "action.yml"
          dangerous_files: "mainTest.cpp"
